//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public int PessoaId { get; set; }
        public string Email { get; set; }
        public byte[] Senha { get; set; }
        public string Nome { get; set; }
        public System.DateTime Nascimento { get; set; }
        public string Telefone { get; set; }
        public short Peso { get; set; }
        public short Altura { get; set; }
        public bool Sexo { get; set; }
    }
}
