//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remedio
    {
        public int RemedioId { get; set; }
        public int PessoaId { get; set; }
        public string Nome { get; set; }
        public byte IntervaloHoras { get; set; }
        public Nullable<System.DateTime> DataUltimaDoseAdministrada { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
