//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Username
    {
        public int UsernameId { get; set; }
        public string Email { get; set; }
        public byte[] Password { get; set; }
    }
}
